#
# Copyright 2019 isobar. All Rights Reserved.
#
# 2019ncku backend
#
# Usage:
#       dk build -t docker-nodejs-2019ncku-backend:1.0.0 -f Dockerfile-nodejs-2019ncku-backend .
#
FROM node:8.16-alpine
LABEL maintainer "jacky.huang@isobar.com"

WORKDIR /home/Backend

COPY . .
RUN npm install

# Define default command.
CMD ["npm", "start"]
